version: "3.8"

services:
  postgres:
    image: postgres:15.1-alpine
    restart: always
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  annie-mei:
    build:
      context: ../
      dockerfile: Dockerfile

volumes:
  pgdata:
