pub mod anilist_anime;
pub mod anilist_common;
pub mod anilist_manga;
pub mod fetcher;
pub mod id_response;
pub mod mal_response;
pub mod media_list_response;
pub mod media_type;
pub mod transformers;
