on:
  push:
    paths-ignore:
      - "**/README.md"
    tags:
      - "**"

name: ARMv7 build

jobs:
  linux_arm7:
    name: Linux ARMv7
    runs-on: ubuntu-latest
    steps:
      - name: Build-checkout
        uses: actions/checkout@v3
      - name: Install Rust
        run: rustup update stable && rustup default stable
      - name: Build-cargo-cross
        uses: actions-rs/cargo@v1
        with:
          use-cross: true
          command: build
          args: --target armv7-unknown-linux-gnueabihf --release
      - name: Check dir
        run: ls target/armv7-unknown-linux-gnueabihf
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: annie-mai-armv7
          path: target/armv7-unknown-linux-gnueabihf/release/annie-mai
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/armv7-unknown-linux-gnueabihf/release/annie-mai
            LICENSE
